version: '2'

services:
  wikibase:
    image: wikibase/wikibase
    build:
      context: ./wikibase
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - /var/www/html/images
  mysql:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  wdqs-frontend:
    image: wikibase/wdqs-frontend
    build:
      context: ./wdqs-frontend
      dockerfile: Dockerfile
    environment:
     - LANGUAGE=en
     - BRAND_TITLE=LocalDockerQuery
     - SPARQL_URI=http://localhost:8989/bigdata/namespace/wdq/sparql
     - WIKIBASE_API=https://www.wikidata.org/w/api.php
    ports:
     - "8282:80"
  wdqs:
    image: wikibase/wdqs
    build:
      context: ./wdqs
      dockerfile: Dockerfile
    ports:
     - "8999:9999"
  wdqs-proxy:
    image: nginx:stable-alpine
    environment:
      - PROXY_PASS_HOST=wdqs:9999
    volumes:
     - ./wdqs-proxy/wdqs.template:/etc/nginx/conf.d/wdqs.template
    ports:
     - "8989:80"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/wdqs.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  wdqs-updater:
    image: wikibase/wdqs-updater
    build:
      context: ./wdqs-updater
      dockerfile: Dockerfile
    depends_on:
    - wdqs
    - wikibase