version: '2'

services:
  wdqs-frontend:
    build:
      context: ./wdqs-frontend
      dockerfile: Dockerfile
    environment:
     - LANGUAGE=en
     - BRAND_TITLE=LocalDockerQuery
     - SPARQL_URI=http://localhost:8989/bigdata/namespace/wdq/sparql
     - WIKIBASE_API=https://www.wikidata.org/w/api.php
    ports:
     - "8080:80"
  wdqs:
    build:
      context: ./wdqs
      dockerfile: Dockerfile
    environment:
      - WIKIBASE_HOSTNAME=www.wikidata.org
  wdqs-proxy:
    image: nginx:stable-alpine
    environment:
      - PROXY_PASS_HOST=wdqs:9999
    volumes:
     - ./wdqs-proxy/wdqs.template:/etc/nginx/conf.d/wdqs.template
    ports:
     - "8989:80"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/wdqs.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  wdqs-updater:
    build:
      context: ./wdqs-updater
      dockerfile: Dockerfile
    environment:
      - WIKIBASE_HOSTNAME=www.wikidata.org
      - QUERY_SERVICE_BACKEND=wdqs:9999